# week3 事前課題3 行列積

## 【問題1】行列積を手計算する

In [4]:
import numpy as np

a_ndarray = np.array([[-1,2,3],
                      [4,-5,6],
                      [7,8,-9]])
b_ndarray = np.array([[0,2,1],
                      [0,2,-8],
                      [2,9,-1]])


answer = np.zeros((3,3))

#手計算
#一行目 
answer[0,0] = (a_ndarray[0,0]*b_ndarray[0,0]
               + a_ndarray[0,1]*b_ndarray[1,0]
               + a_ndarray[0,2]*b_ndarray[2,0])
                 
answer[0,1] = (a_ndarray[0,0]*b_ndarray[0,1]
               + a_ndarray[0,1]*b_ndarray[1,1]
               + a_ndarray[0,2]*b_ndarray[2,1])

answer[0,2] = (a_ndarray[0,0]*b_ndarray[0,2]
               + a_ndarray[0,1]*b_ndarray[1,2]
               + a_ndarray[0,2]*b_ndarray[2,2])

#二行目 
answer[1,0] = (a_ndarray[1,0]*b_ndarray[0,0]
               + a_ndarray[1,1]*b_ndarray[1,0]
               + a_ndarray[1,2]*b_ndarray[2,0])

answer[1,1] = (a_ndarray[1,0]*b_ndarray[0,1]
               + a_ndarray[1,1]*b_ndarray[1,1]
               + a_ndarray[1,2]*b_ndarray[2,1])

answer[1,2] =  (a_ndarray[1,0]*b_ndarray[0,2]
               + a_ndarray[1,1]*b_ndarray[1,2]
               + a_ndarray[1,2]*b_ndarray[2,2])

#三行目
answer[2,0] =  (a_ndarray[2,0]*b_ndarray[0,0]
               + a_ndarray[2,1]*b_ndarray[1,0]
               + a_ndarray[2,2]*b_ndarray[2,0])

answer[2,1] =  (a_ndarray[2,0]*b_ndarray[0,1]
               + a_ndarray[2,1]*b_ndarray[1,1]
               + a_ndarray[2,2]*b_ndarray[2,1])

answer[2,2] =  (a_ndarray[2,0]*b_ndarray[0,2]
               + a_ndarray[2,1]*b_ndarray[1,2]
               + a_ndarray[2,2]*b_ndarray[2,2])


print(answer)

[[  6.  29. -20.]
 [ 12.  52.  38.]
 [-18. -51. -48.]]


## 【問題2】NumPyの関数による計算

In [2]:
a_ndarray @ b_ndarray 

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

## 【問題3】ある要素の計算を実装
>np.matmul()やnp.dot()、または@演算子を使わずに行うコードを書いてください。

In [57]:
#a[0,k]*b[k,0] を　range(０:3)で繰り返して総和を求める
list_k=[]

for k in range(a_ndarray.shape[0]):
    inside_sums = a_ndarray[0,k]*b_ndarray[k,0]
    list_k.append(inside_sums)
    #print(list_k)
    
print(sum(list_k))

6


## 【問題4】行列積を行う関数の作成

In [5]:
def fuckinarraysum(l=a_ndarray,r=b_ndarray):
    list_array = []
    list_sums = []
    list_temp = []
    
    for i in range(l.shape[0]):
        list_sums = []
        
        for j in range(l.shape[0]):
            list_temp = []
            
            for k in range(l.shape[0]):
                inside_sums = a_ndarray[i,k]*b_ndarray[k,j]
                list_temp.append(inside_sums)
            list_sums.append(sum(list_temp)) #リストにシュート
            
        list_array.append(list_sums) #リストにシュート
            
    return list_array
            


print(fuckinarraysum(a_ndarray,b_ndarray))


#完成

[[6, 29, -20], [12, 52, 38], [-18, -51, -48]]


## 【問題5】計算が定義されない入力を判定する

In [6]:
a_ndarray = np.array([[-1,2,3],
                      [4,-5,6],
                      [7,8,-9]])
b_ndarray = np.array([[0,2,1],
                      [0,2,-8],
                      [2,9,-1]])

def arrayhell(l=a_ndarray, r=b_ndarray):
    if l.shape[0] == r.shape[1]:
        answer = fuckinarraysum(a_ndarray,b_ndarray)
                    
    else:
         answer = print("ERROR: 右の列数と左の行数が不一致。")
        
    return answer

print(arrayhell())

[[6, 29, -20], [12, 52, 38], [-18, -51, -48]]


In [7]:
d_ndarray = np.array([[-1,2,3],
                      [4,-5,6]])
e_ndarray = np.array([[-9,8,7],
                      [6,-5,4]])

print(arrayhell(d_ndarray,e_ndarray))

ERROR: 右の列数と左の行数が不一致。
None


## 【問題6】転置

In [8]:
e_ndarray_t = e_ndarray.T
print(e_ndarray_t)

[[-9  6]
 [ 8 -5]
 [ 7  4]]


In [10]:
d_ndarray @ e_ndarray_t

array([[ 46,  -4],
       [-34,  73]])